# Generated by Django 2.2 on 2019-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sprite', models.FileField(upload_to='sprites')),
                ('model3d', models.FileField(upload_to='models3d')),
            ],
        ),
    ]
