# Generated by Django 2.2.1 on 2019-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprite',
            name='heightMap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='model3d',
            field=models.FileField(blank=True, upload_to='models3d'),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='sprite',
            field=models.FileField(blank=True, upload_to='sprites'),
        ),
    ]
