# Generated by Django 2.2.2 on 2019-06-16 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0002_auto_20190530_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixelMap', to='pixel3Dapp.Sprite')),
            ],
        ),
        migrations.CreateModel(
            name='PixelRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('pixelMap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pixel3Dapp.PixelMap')),
            ],
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.IntegerField()),
                ('pixelRow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='pixel3Dapp.PixelRow')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField()),
                ('g', models.IntegerField()),
                ('b', models.IntegerField()),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='pixel3Dapp.Pixel', unique=True)),
            ],
        ),
    ]
