# Generated by Django 2.2.2 on 2019-06-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0003_color_pixel_pixelmap_pixelrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='pixelmap',
            name='sprite',
        ),
        migrations.AddField(
            model_name='sprite',
            name='pixelMap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel3Dapp.PixelMap'),
        ),
        migrations.CreateModel(
            name='ColorMapItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField()),
                ('g', models.IntegerField()),
                ('b', models.IntegerField()),
                ('h', models.IntegerField()),
                ('colorMap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorMapItems', to='pixel3Dapp.ColorMap')),
            ],
        ),
        migrations.AddField(
            model_name='sprite',
            name='colorMap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel3Dapp.ColorMap'),
        ),
    ]
