# Generated by Django 2.2.2 on 2019-06-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0004_auto_20190616_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='pixel',
        ),
        migrations.AddField(
            model_name='pixel',
            name='color',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel3Dapp.Color'),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='colorMap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel3Dapp.ColorMap'),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='pixelMap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel3Dapp.PixelMap'),
        ),
    ]
