# Generated by Django 2.2.2 on 2019-06-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0005_auto_20190616_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixel',
            old_name='y',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='pixelrow',
            old_name='x',
            new_name='y',
        ),
    ]
