# Generated by Django 2.2.2 on 2019-06-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0007_remove_sprite_heightmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelmap',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixelmap',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
