# Generated by Django 2.2.2 on 2019-06-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0008_auto_20190616_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colormapitem',
            name='h',
            field=models.FloatField(),
        ),
    ]
