# Generated by Django 2.2.2 on 2019-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0009_auto_20190616_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormap',
            name='maxHeight',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='colormap',
            name='pixelSize',
            field=models.FloatField(default=10),
        ),
    ]
