# Generated by Django 2.2.2 on 2019-06-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0010_auto_20190617_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprite',
            name='colorMap',
        ),
        migrations.AddField(
            model_name='colormap',
            name='sprite',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colorMap', to='pixel3Dapp.Sprite'),
        ),
    ]
