# Generated by Django 2.2.2 on 2019-06-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel3Dapp', '0011_auto_20190617_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprite',
            name='pixelMap',
        ),
        migrations.AddField(
            model_name='pixelmap',
            name='sprite',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pixelMap', to='pixel3Dapp.Sprite'),
        ),
    ]
